# Generated by Django 4.2.4 on 2023-12-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
